### ISSUE TITLE
Unable to run Gulp

### ISSUE THREAD

**Issue by Hyllesen** [Skippeh/calcrust.com-frontend#6]
Hello

When I try to run the project with the `gulp` command after npm install, I get the error:

```
/home/stefan/calcrust.com-frontend/gulpfile.js:25
gulp.task("usemin", () => {
                     ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at execute (/usr/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp-cli/index.js:149:63)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/lib/node_modules/gulp-cli/node_modules/flagged-respawn/index.js:17:3)
```

This is my installed gulp packages:

>  npm ls | grep gulp
> ├─┬ gulp@3.9.1
> │ ├─┬ gulp-util@3.0.7
> │ │ ├─┬ gulplog@1.0.0
> │ │ ├─┬ has-gulplog@0.1.0
> ├─┬ gulp-babel@6.1.2
> ├─┬ gulp-connect@4.2.0
> ├─┬ gulp-hash-src@0.1.6
> ├─┬ gulp-htmlmin@2.0.0
> ├─┬ gulp-less@3.1.0
> ├─┬ gulp-livereload@3.8.1
> ├─┬ gulp-minify-css@1.2.4
> ├─┬ gulp-ng-html2js@0.2.2
> ├─┬ gulp-print@2.0.1
> ├── gulp-rename@1.2.2
> ├─┬ gulp-sass@2.3.2
> ├─┬ gulp-uglify@1.5.4
> ├─┬ gulp-usemin@0.3.23
> │ ├─┬ gulp-concat@2.4.3
> │ ├─┬ gulp-util@2.2.20
> └─┬ gulp-watch@4.3.9
>

**Comment by amPerl** [comment]
What's your node version?

**Comment by Skippeh** [comment]
Are you running a version of node that has es6 support?

**Comment by Hyllesen** [comment]
I updated my nodejs with

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
npm rebuild node-sass
```
Was able to run it afterwards! Thanks a lot!
